version: '3'

services:
  db:
    image: postgres
  migration:
  build: .
  command: python manage.py migrate
    volumes:
      - .:/home/concytec/PycharmProjects/django/api-encuesta
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/concytec/PycharmProjects/django/api-encuesta
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration

