# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='author',
        ),
    ]
