# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuestas', '0003_encuesta_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='opcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='encuestas.OpcionPregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='voted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuestas.Pregunta'),
        ),
    ]
